# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"dataset_url": "00_Datasets.ipynb",
         "dataset_root": "00_Datasets.ipynb",
         "dataset_zip": "00_Datasets.ipynb",
         "DolphinsInstanceSegmentationDataset": "00_Datasets.ipynb",
         "get_dataset": "00_Datasets.ipynb"}

modules = ["datasets.py"]

doc_url = "https://pages.github.cro-ai-league.com./dolphins-recognition-challenge/dolphins_recognition_challenge/"

git_url = "https://github.cro-ai-league.com/dolphins-recognition-challenge/dolphins_recognition_challenge/tree/master/"

def custom_doc_links(name): return None
