# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_dataset": "00_Dataset.ipynb"}

modules = ["datasets.py"]

doc_url = "https://pages.github.cro-ai-league.com./dolphins-recognition-challenge/dolphins_recognition_challenge/"

git_url = "https://github.cro-ai-league.com/dolphins-recognition-challenge/dolphins_recognition_challenge/tree/master/"

def custom_doc_links(name): return None
