# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/01_Dolphin_instance_segmentation_challenge.ipynb (unless otherwise specified).

__all__ = []

# Cell

from pathlib import Path
from typing import List, Tuple, Union, Optional, Dict, Set

# Internal Cell

import numpy as np
import os
from datetime import datetime
import torch
import torch.utils.data
from torch.hub import download_url_to_file
import torchvision
import PIL
from PIL import Image
from zipfile import ZipFile

from torchvision.models.detection.faster_rcnn import FastRCNNPredictor
from torchvision.models.detection.mask_rcnn import MaskRCNNPredictor

for m in [np, torch, torchvision, PIL]:
    print(f"{m.__name__:12}: {m.__version__}")