# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/96_Leaderboard.ipynb (unless otherwise specified).

__all__ = ['get_leaderboard']

# Internal Cell

import pandas as pd

# Cell

def get_leaderboard():
    df = pd.DataFrame(dict(alias=["davor", "matija", "leptirić"], score=[0.483, 0.453, 0.526]))

    return df.sort_values(by="score", ascending=False).reset_index(drop=True)